CREATE TABLE IF NOT EXISTS `crawl_country` (
  `code` char(2) NOT NULL,
  `name` varchar(50) NOT NULL,
  `slug` varchar(50) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `crawl_country` (`code`, `name`, `slug`) VALUES
('84', 'Da Nang', 'da-nang'),
('AD', 'Andorra', 'andorra'),
('AE', 'United Arab Emirates', 'united-arab-emirates'),
('AF', 'Afghanistan', 'afghanistan'),
('AG', 'Antigua and Barbuda', 'antigua-and-barbuda'),
('AI', 'Anguilla', 'anguilla'),
('AL', 'Albania', 'albania'),
('AM', 'Armenia', 'armenia'),
('AO', 'Angola', 'angola'),
('AQ', 'Antarctica', 'antarctica'),
('AR', 'Argentina', 'argentina'),
('AS', 'American Samoa', 'american-samoa'),
('AT', 'Austria', 'austria'),
('AU', 'Australia', 'australia'),
('AW', 'Aruba', 'aruba'),
('AX', 'Åland Islands', 'aland-islands'),
('AZ', 'Azerbaijan', 'azerbaijan'),
('BA', 'Bosnia and Herzegovina', 'bosnia-and-herzegovina'),
('BB', 'Barbados', 'barbados'),
('BD', 'Bangladesh', 'bangladesh'),
('BE', 'Belgium', 'belgium'),
('BF', 'Burkina Faso', 'burkina-faso'),
('BG', 'Bulgaria', 'bulgaria'),
('BH', 'Bahrain', 'bahrain'),
('BI', 'Burundi', 'burundi'),
('BJ', 'Benin', 'benin'),
('BL', 'Saint Barthélemy', 'saint-barthelemy'),
('BM', 'Bermuda', 'bermuda'),
('BN', 'Brunei Darussalam', 'brunei-darussalam'),
('BO', 'Bolivia, Plurinational State of', 'bolivia-plurinational-state-of'),
('BQ', 'Bonaire, Sint Eustatius and Saba', 'bonaire-sint-eustatius-and-saba'),
('BR', 'Brazil', 'brazil'),
('BS', 'Bahamas', 'bahamas'),
('BT', 'Bhutan', 'bhutan'),
('BV', 'Bouvet Island', 'bouvet-island'),
('BW', 'Botswana', 'botswana'),
('BY', 'Belarus', 'belarus'),
('BZ', 'Belize', 'belize'),
('CA', 'Canada', 'canada'),
('CC', 'Cocos (Keeling) Islands', 'cocos-keeling-islands'),
('CD', 'Congo, the Democratic Republic of the', 'congo-the-democratic-republic-of-the'),
('CF', 'Central African Republic', 'central-african-republic'),
('CG', 'Congo', 'congo'),
('CH', 'Switzerland', 'switzerland'),
('CI', 'Côte d''Ivoire', 'cote-d-ivoire'),
('CK', 'Cook Islands', 'cook-islands'),
('CL', 'Chile', 'chile'),
('CM', 'Cameroon', 'cameroon'),
('CN', 'China', 'china'),
('CO', 'Colombia', 'colombia'),
('CR', 'Costa Rica', 'costa-rica'),
('CU', 'Cuba', 'cuba'),
('CV', 'Cape Verde', 'cape-verde'),
('CW', 'Curaçao', 'curacao'),
('CX', 'Christmas Island', 'christmas-island'),
('CY', 'Cyprus', 'cyprus'),
('CZ', 'Czech Republic', 'czech-republic'),
('DE', 'Germany', 'germany'),
('DJ', 'Djibouti', 'djibouti'),
('DK', 'Denmark', 'denmark'),
('DM', 'Dominica', 'dominica'),
('DO', 'Dominican Republic', 'dominican-republic'),
('DZ', 'Algeria', 'algeria'),
('EC', 'Ecuador', 'ecuador'),
('EE', 'Estonia', 'estonia'),
('EG', 'Egypt', 'egypt'),
('EH', 'Western Sahara', 'western-sahara'),
('ER', 'Eritrea', 'eritrea'),
('ES', 'Spain', 'spain'),
('ET', 'Ethiopia', 'ethiopia'),
('FI', 'Finland', 'finland'),
('FJ', 'Fiji', 'fiji'),
('FK', 'Falkland Islands (Malvinas)', 'falkland-islands-malvinas'),
('FM', 'Micronesia, Federated States of', 'micronesia-federated-states-of'),
('FO', 'Faroe Islands', 'faroe-islands'),
('FR', 'France', 'france'),
('GA', 'Gabon', 'gabon'),
('GB', 'United Kingdom', 'united-kingdom'),
('GD', 'Grenada', 'grenada'),
('GE', 'Georgia', 'georgia'),
('GF', 'French Guiana', 'french-guiana'),
('GG', 'Guernsey', 'guernsey'),
('GH', 'Ghana', 'ghana'),
('GI', 'Gibraltar', 'gibraltar'),
('GL', 'Greenland', 'greenland'),
('GM', 'Gambia', 'gambia'),
('GN', 'Guinea', 'guinea'),
('GP', 'Guadeloupe', 'guadeloupe'),
('GQ', 'Equatorial Guinea', 'equatorial-guinea'),
('GR', 'Greece', 'greece'),
('GS', 'South Georgia and the South Sandwich Islands', 'south-georgia-and-the-south-sandwich-islands'),
('GT', 'Guatemala', 'guatemala'),
('GU', 'Guam', 'guam'),
('GW', 'Guinea-Bissau', 'guinea-bissau'),
('GY', 'Guyana', 'guyana'),
('HK', 'Hong Kong', 'hong-kong'),
('HM', 'Heard Island and McDonald Islands', 'heard-island-and-mcdonald-islands'),
('HN', 'Honduras', 'honduras'),
('HR', 'Croatia', 'croatia'),
('HT', 'Haiti', 'haiti'),
('HU', 'Hungary', 'hungary'),
('ID', 'Indonesia', 'indonesia'),
('IE', 'Ireland', 'ireland'),
('IL', 'Israel', 'israel'),
('IM', 'Isle of Man', 'isle-of-man'),
('IN', 'India', 'india'),
('IO', 'British Indian Ocean Territory', 'british-indian-ocean-territory'),
('IQ', 'Iraq', 'iraq'),
('IR', 'Iran, Islamic Republic of', 'iran-islamic-republic-of'),
('IS', 'Iceland', 'iceland'),
('IT', 'Italy', 'italy'),
('JE', 'Jersey', 'jersey'),
('JM', 'Jamaica', 'jamaica'),
('JO', 'Jordan', 'jordan'),
('JP', 'Japan', 'japan'),
('KE', 'Kenya', 'kenya'),
('KG', 'Kyrgyzstan', 'kyrgyzstan'),
('KH', 'Cambodia', 'cambodia'),
('KI', 'Kiribati', 'kiribati'),
('KM', 'Comoros', 'comoros'),
('KN', 'Saint Kitts and Nevis', 'saint-kitts-and-nevis'),
('KP', 'Korea, Democratic People''s Republic of', 'korea-democratic-people-s-republic-of'),
('KR', 'South Korea', 'south-korea'),
('KW', 'Kuwait', 'kuwait'),
('KY', 'Cayman Islands', 'cayman-islands'),
('KZ', 'Kazakhstan', 'kazakhstan'),
('LA', 'Lao People''s Democratic Republic', 'lao-people-s-democratic-republic'),
('LB', 'Lebanon', 'lebanon'),
('LC', 'Saint Lucia', 'saint-lucia'),
('LI', 'Liechtenstein', 'liechtenstein'),
('LK', 'Sri Lanka', 'sri-lanka'),
('LR', 'Liberia', 'liberia'),
('LS', 'Lesotho', 'lesotho'),
('LT', 'Lithuania', 'lithuania'),
('LU', 'Luxembourg', 'luxembourg'),
('LV', 'Latvia', 'latvia'),
('LY', 'Libya', 'libya'),
('MA', 'Morocco', 'morocco'),
('MC', 'Monaco', 'monaco'),
('MD', 'Moldova, Republic of', 'moldova-republic-of'),
('ME', 'Montenegro', 'montenegro'),
('MF', 'Saint Martin (French part)', 'saint-martin-french-part'),
('MG', 'Madagascar', 'madagascar'),
('MH', 'Marshall Islands', 'marshall-islands'),
('MK', 'Macedonia, the former Yugoslav Republic of', 'macedonia-the-former-yugoslav-republic-of'),
('ML', 'Mali', 'mali'),
('MM', 'Myanmar', 'myanmar'),
('MN', 'Mongolia', 'mongolia'),
('MO', 'Macao', 'macao'),
('MP', 'Northern Mariana Islands', 'northern-mariana-islands'),
('MQ', 'Martinique', 'martinique'),
('MR', 'Mauritania', 'mauritania'),
('MS', 'Montserrat', 'montserrat'),
('MT', 'Malta', 'malta'),
('MU', 'Mauritius', 'mauritius'),
('MV', 'Maldives', 'maldives'),
('MW', 'Malawi', 'malawi'),
('MX', 'Mexico', 'mexico'),
('MY', 'Malaysia', 'malaysia'),
('MZ', 'Mozambique', 'mozambique'),
('NA', 'Namibia', 'namibia'),
('NC', 'New Caledonia', 'new-caledonia'),
('NE', 'Niger', 'niger'),
('NF', 'Norfolk Island', 'norfolk-island'),
('NG', 'Nigeria', 'nigeria'),
('NI', 'Nicaragua', 'nicaragua'),
('NL', 'Netherlands', 'netherlands'),
('NO', 'Norway', 'norway'),
('NP', 'Nepal', 'nepal'),
('NR', 'Nauru', 'nauru'),
('NU', 'Niue', 'niue'),
('NZ', 'New Zealand', 'new-zealand'),
('OM', 'Oman', 'oman'),
('PA', 'Panama', 'panama'),
('PE', 'Peru', 'peru'),
('PF', 'French Polynesia', 'french-polynesia'),
('PG', 'Papua New Guinea', 'papua-new-guinea'),
('PH', 'Philippines', 'philippines'),
('PK', 'Pakistan', 'pakistan'),
('PL', 'Poland', 'poland'),
('PM', 'Saint Pierre and Miquelon', 'saint-pierre-and-miquelon'),
('PN', 'Pitcairn', 'pitcairn'),
('PR', 'Puerto Rico', 'puerto-rico'),
('PS', 'Palestine, State of', 'palestine-state-of'),
('PT', 'Portugal', 'portugal'),
('PW', 'Palau', 'palau'),
('PY', 'Paraguay', 'paraguay'),
('QA', 'Qatar', 'qatar'),
('RE', 'Réunion', 'reunion'),
('RO', 'Romania', 'romania'),
('RS', 'Serbia', 'serbia'),
('RU', 'Russian Federation', 'russian-federation'),
('RW', 'Rwanda', 'rwanda'),
('SA', 'Saudi Arabia', 'saudi-arabia'),
('SB', 'Solomon Islands', 'solomon-islands'),
('SC', 'Seychelles', 'seychelles'),
('SD', 'Sudan', 'sudan'),
('SE', 'Sweden', 'sweden'),
('SG', 'Singapore', 'singapore'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'saint-helena-ascension-and-tristan-da-cunha'),
('SI', 'Slovenia', 'slovenia'),
('SJ', 'Svalbard and Jan Mayen', 'svalbard-and-jan-mayen'),
('SK', 'Slovakia', 'slovakia'),
('SL', 'Sierra Leone', 'sierra-leone'),
('SM', 'San Marino', 'san-marino'),
('SN', 'Senegal', 'senegal'),
('SO', 'Somalia', 'somalia'),
('SR', 'Suriname', 'suriname'),
('SS', 'South Sudan', 'south-sudan'),
('ST', 'Sao Tome and Principe', 'sao-tome-and-principe'),
('SV', 'El Salvador', 'el-salvador'),
('SX', 'Sint Maarten (Dutch part)', 'sint-maarten-dutch-part'),
('SY', 'Syrian Arab Republic', 'syrian-arab-republic'),
('SZ', 'Swaziland', 'swaziland'),
('TC', 'Turks and Caicos Islands', 'turks-and-caicos-islands'),
('TD', 'Chad', 'chad'),
('TF', 'French Southern Territories', 'french-southern-territories'),
('TG', 'Togo', 'togo'),
('TH', 'Thailand', 'thailand'),
('TJ', 'Tajikistan', 'tajikistan'),
('TK', 'Tokelau', 'tokelau'),
('TL', 'Timor-Leste', 'timor-leste'),
('TM', 'Turkmenistan', 'turkmenistan'),
('TN', 'Tunisia', 'tunisia'),
('TO', 'Tonga', 'tonga'),
('TR', 'Turkey', 'turkey'),
('TT', 'Trinidad and Tobago', 'trinidad-and-tobago'),
('TV', 'Tuvalu', 'tuvalu'),
('TW', 'Taiwan', 'taiwan'),
('TZ', 'Tanzania, United Republic of', 'tanzania-united-republic-of'),
('UA', 'Ukraine', 'ukraine'),
('UG', 'Uganda', 'uganda'),
('UM', 'United States Minor Outlying Islands', 'united-states-minor-outlying-islands'),
('US', 'United States', 'united-states'),
('UY', 'Uruguay', 'uruguay'),
('UZ', 'Uzbekistan', 'uzbekistan'),
('VA', 'Holy See (Vatican City State)', 'holy-see-vatican-city-state'),
('VC', 'Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines'),
('VE', 'Venezuela, Bolivarian Republic of', 'venezuela-bolivarian-republic-of'),
('VG', 'Virgin Islands, British', 'virgin-islands-british'),
('VI', 'Virgin Islands, U.S.', 'virgin-islands-u-s'),
('VN', 'Vietnam', 'vietnam'),
('VU', 'Vanuatu', 'vanuatu'),
('WF', 'Wallis and Futuna', 'wallis-and-futuna'),
('WS', 'Samoa', 'samoa'),
('YE', 'Yemen', 'yemen'),
('YT', 'Mayotte', 'mayotte'),
('ZA', 'South Africa', 'south-africa'),
('ZM', 'Zambia', 'zambia'),
('ZW', 'Zimbabwe', 'zimbabwe');

CREATE TABLE IF NOT EXISTS `crawl_city` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_id` char(2) NOT NULL,
  `name` varchar(50) NOT NULL,
  `slug` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `crawl_city_d860be3c` (`country_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3576072 ;

INSERT INTO `crawl_city` (`id`, `country_id`, `name`, `slug`) VALUES
(293913, 'TW', 'Taipei', 'taipei'),
(293916, 'TH', 'Bangkok', 'bangkok'),
(293920, 'TH', 'Phuket', 'phuket'),
(293924, 'VN', 'Hanoi', 'hanoi'),
(293925, 'VN', 'Ho Chi Minh', 'ho-chi-minh'),
(293940, 'KH', 'Phnom Penh', 'phnom-penh'),
(294197, 'KR', 'Seoul', 'seoul'),
(294212, 'CN', 'Beijing', 'beijing'),
(294217, 'CN', 'Hong Kong', 'hong-kong'),
(294226, 'ID', 'Bali', 'bali'),
(294261, 'PH', 'Cebu', 'cebu'),
(294262, 'SG', 'Singapore', 'singapore'),
(295408, 'MM', 'Mandalay', 'mandalay'),
(297390, 'KH', 'Siem Reap', 'siem-reap'),
(297885, 'KR', 'Jeju', 'jeju'),
(298082, 'VN', 'Hoi An', 'hoi-an'),
(298184, 'JP', 'Tokyo', 'tokyo'),
(298302, 'MY', 'Penang', 'penang'),
(298559, 'CN', 'Hangzhou', 'hangzhou'),
(298566, 'JP', 'Osaka', 'osaka'),
(298570, 'MY', 'Kuala Lumpur', 'kuala-lumpur'),
(298573, 'PH', 'Manila', 'manila'),
(308272, 'CN', 'Shanghai', 'shanghai'),
(317112, 'MM', 'Bagan', 'bagan'),
(664891, 'CN', 'Macau', 'macau'),
(3576037, 'MM', 'Yangon', 'yangon'),
(3576039, 'MY', 'Kota Kinabalu', 'kota-kinabalu'),
(3576040, 'MY', 'Kuching', 'kuching'),
(3576041, 'MY', 'Langkawi', 'langkawi'),
(3576042, 'ID', 'Bandung', 'bandung'),
(3576043, 'ID', 'Jakarta', 'jakarta'),
(3576044, 'ID', 'Yogyakarta', 'yogyakarta'),
(3576045, 'PH', 'Boracay', 'boracay'),
(3576046, 'PH', 'Davao', 'davao'),
(3576047, 'PH', 'Iloilo', 'iloilo'),
(3576048, 'ID', 'Surabaya', 'surabaya'),
(3576049, 'ID', 'Padang', 'padang'),
(3576050, 'ID', 'Lombok', 'lombok'),
(3576051, 'PH', 'Bacolod', 'bacolod'),
(3576052, 'PH', 'Puerto Princesa', 'puerto-princesa'),
(3576053, 'PH', 'Tacloban', 'tacloban'),
(3576054, 'ID', 'Medan', 'medan'),
(3576055, 'SG', 'Sentosa Island', 'sentosa-island'),
(3576056, 'AU', 'Sydney', 'sydney'),
(3576057, 'AU', 'Melbourne', 'melbourne'),
(3576058, 'MV', 'Maldives', 'maldives'),
(3576059, 'VN', 'Phu Quoc', 'phu-quoc'),
(3576060, 'VN', 'Da Nang', 'da-nang'),
(3576061, 'TH', 'Ao Nang', 'ao-nang'),
(3576063, 'MY', 'Cameron Highlands', 'cameron-highlands'),
(3576064, 'TH', 'Chiang Mai', 'chiang-mai'),
(3576065, 'VN', 'Sapa', 'sapa'),
(3576066, 'VN', 'Hue', 'hue'),
(3576067, 'VN', 'Nha Trang', 'nha-trang'),
(3576068, 'VN', 'Mui Ne', 'mui-ne'),
(3576069, 'VN', 'Mekong Delta', 'mekong-delta'),
(3576070, 'KH', 'Sihanoukville', 'sihanoukville'),
(3576071, 'AU', 'Brisbane', 'brisbane');

ALTER TABLE `crawl_city`
  ADD CONSTRAINT `country_id_refs_code_11bc5f9f` FOREIGN KEY (`country_id`) REFERENCES `crawl_country` (`code`);